version: "3.2"
services:
  api:
    image: flask_api
    container_name: ml_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - model
    volumes:
      - ./feedback:/src/feedback
      - ./uploads:/src/static/uploads
      #- ./api:/src # Used in development to edit files live
    # command: --reload # Used in development to reload on every change
    networks:
    - sprint4-net

  redis:
    image: redis:6.2.6
    networks:
    - sprint4-net

  model:
    image: ml_service
    build:
      context: ./model
      target: build
    depends_on:
      - redis
    volumes:
      - ./uploads:/src/uploads
    networks:
    - sprint4-net
    environment:
      - PYTHONUNBUFFERED=1

networks:
  sprint4-net:
    driver: bridge